mappings:
  GridFieldAddNewSiteTreeItemButton: Restruct\Silverstripe\SiteTreeButtons\GridFieldAddNewSiteTreeItemButton
  GridFieldEditSiteTreeItemButton: Restruct\Silverstripe\SiteTreeButtons\GridFieldEditSiteTreeItemButton
